### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by wanlinandkunping** [LunziSTU/tp-sms#3]
生成登录（login）场景的验证码并缓存
$code = (new TpSms())->scene('login')->create();

错误提示：
Call to a member function create() on null

**Comment by indiboy** [comment]
是的，我这里也是，不能添加场景。

**Comment by indiboy** [comment]
不是不能添加场景，就是需要随机配置，不能配置到一个文件。

**Comment by LunziSTU** [comment]
改 bug 已修复
